export enum DeviceType {
    NONE = 'NONE', CONTROLLINGTHEGATEWAYLOCK = 'CONTROLLINGTHEGATEWAYLOCK', CONTROLLINGTHEGATE = 'CONTROLLINGTHEGATE',
    CONTROLLINGTHEGARAGEDOOR = 'CONTROLLINGTHEGARAGEDOOR',
    THERMOMETER = 'THERMOMETER', HUMIDITY = 'HUMIDITY', HUMIDITYANDTEMPERATURE = 'HUMIDITYANDTEMPERATURE', OPENINGSENSOR_GATEWAY = 'OPENINGSENSOR_GATEWAY',
    OPENINGSENSOR_GATE = 'OPENINGSENSOR_GATE', OPENINGSENSOR_GARAGEDOOR = 'OPENINGSENSOR_GARAGEDOOR', NOLIQUIDSENSOR = 'NOLIQUIDSENSOR',
    CONTROLLINGTHEDOORLOCK = 'CONTROLLINGTHEDOORLOCK', OPENINGSENSOR_DOOR = 'OPENINGSENSOR_DOOR', CONTROLLINGTHEROLLERSHUTTER = 'CONTROLLINGTHEROLLERSHUTTER',
    OPENINGSENSOR_ROLLERSHUTTER = 'OPENINGSENSOR_ROLLERSHUTTER', POWERSWITCH = 'POWERSWITCH', LIGHTSWITCH = 'LIGHTSWITCH', DIMMER = 'DIMMER',
    RGBLIGHTING = 'RGBLIGHTING', DIMMERANDRGBLIGHTING = 'DIMMERANDRGBLIGHTING', DEPTHSENSOR = 'DEPTHSENSOR', DISTANCESENSOR = 'DISTANCESENSOR',
    OPENINGSENSOR_WINDOW = 'OPENINGSENSOR_WINDOW', MAILSENSOR = 'MAILSENSOR', WINDSENSOR = 'WINDSENSOR', PRESSURESENSOR = 'PRESSURESENSOR',
    RAINSENSOR = 'RAINSENSOR', WEIGHTSENSOR = 'WEIGHTSENSOR', WEATHER_STATION = 'WEATHER_STATION', STAIRCASETIMER = 'STAIRCASETIMER'
}

export enum ActionType {
    OPEN = 'OPEN', CLOSE = 'CLOSE', SHUT = 'SHUT', REVEAL = 'REVEAL', REVEAL_PARTIALLY = 'REVEAL_PARTIALLY',
    TURN_ON = 'TURN_ON', TURN_OFF = 'TURN_OFF', SET_RGBW_PARAMETERS = 'SET_RGBW_PARAMETERS', OPEN_CLOSE = 'OPEN_CLOSE',
    STOP = 'STOP', TOGGLE = 'TOGGLE', READ = 'READ'
}